# Default values for rode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafeas:
  enabled: true
  storageType: embedded
  container:
    port: 443
  service:
    port: 443
  certificates:
    enabled: true
  secret:
    enabled: true

localstack:
  enabled: false

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

ginMode: release
extraEnv: []

container:
  port: 8080
service:
  port: 8080

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  failureThreshold: 6
  initialDelaySeconds: 0
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

tolerations: []
affinity: {}
podSecurityContext: {}
podLabels: {}
nodeSelector: {}
podAnnotations: {}

replicaCount: 1
minAvailable: 1

resources: 
  limits:
    cpu: 10m
    memory: 20Mi
  requests:
    cpu: 10m
    memory: 20Mi
