{{- if .Values.secret.enabled }}
{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $grafeas_cn := printf "grafeas-server.%s.svc.cluster.local" .Release.Namespace }}
{{ $grafeas_server := genSignedCert $grafeas_cn nil nil 365 $ca }}
{{ $rode_cn := printf "rode.%s.svc.cluster.local" .Release.Namespace }}
{{ $rode_client := genSignedCert $rode_cn nil nil 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafeas.certificates.name }}
  labels:
    app: {{ template "rode.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $grafeas_server.Cert }}
  tls.key: {{ b64enc $grafeas_server.Key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificates.name }}
  labels:
    app: {{ template "rode.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $rode_client.Cert }}
  tls.key: {{ b64enc $rode_client.Key }}
{{- end }}
