{{- if .Values.secret.enabled }}
{{ $ca := genCA "svc-cat-ca" 3650 }}
{{ $cn := printf "grafeas.%s.svc.cluster.local" .Release.Namespace }}
{{ $server := genSignedCert $cn nil nil 365 $ca }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certificates.name }}
  labels:
    app: {{ template "grafeas.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.crt: {{ b64enc $ca.Cert }}
  tls.crt: {{ b64enc $server.Cert }}
  tls.key: {{ b64enc $server.Key }}
{{- end }}
